Modes:
  RaceManager: true
  MobManager: true
  ScoreManager: true
  LivesManager: true
  LifeGifting: true
  AFKChecker: true
  NightHostiles: true
MOBS:
  ZOMBIE:
    NOBABYS: true
    ITEMS:
      HAND: STONE_SWORD
    DROPS:
      PORKCHOP:
        MIN: 0
        MAX: 3
  HUSK:
    BUFFS:
      SIZE:
        BASE: 1.5
        VARIANCE: 0.3
    ITEMS:
      HAND: STONE_SWORD
  DROWNED:
    BUFFS:
      SPEED:
        BASE: 2.0
        VARIANCE: 0.0
  WOLF:
    DROPS:
      ROTTEN_FLESH:
        MIN: 0
        MAX: 2
  CAT:
    DROPS:
      ROTTEN_FLESH:
        MIN: 0
        MAX: 2
  OCELOT:
    DROPS:
      ROTTEN_FLESH:
        MIN: 0
        MAX: 2
  POLAR_BEAR:
    DROPS:
      ROTTEN_FLESH:
        MIN: 0
        MAX: 2
Scoring:
  adventureMultiplier: 1.5
  Death: -10.0
  AdventureDeath: -5.0
  Xp: 0.0001
  OnlineHr: 2.5
  BlocksPlaced: 0.001
  BlocksMined: 0.001
  HarvestedTotal: 0.001
  CaughtTotal: 0.001
  Achevements: 0.3
  MobKills:
    WARDEN: 20.0
    WITHER: 20.0
    ELDER_GUARDIAN: 10.0
    RAVAGER: 6.0
    BREEZE: 4.0
    EVOKER: 3.0
    PIGLIN_BRUTE: 2.0
    WITHER_SKELETON: 2.0
    SHULKER: 1.0
    IRON_GOLEM: 1.0
    VINDICATOR: 1.0
    VEX: 1.0
    WITCH: 0.7
    ENDERMAN: 0.5
    BLAZE: 0.5
    GHAST: 0.5
    GUARDIAN: 0.4
    CAVE_SPIDER: 0.3
    PIGLIN: 0.3
    ZOMBIFIED_PIGLIN: 0.3
    HOGLIN: 0.3
    ZOGLIN: 0.3
    PILLAGER: 0.3
    CREEPER: 0.3
    DROWNED: 0.3
    MAGMA_CUBE: 0.2
    STRAY: 0.2
    BOGGED: 0.2
    PHANTOM: 0.1
    SKELETON: 0.1
    ZOMBIE: 0.1
    HUSK: 0.1
    SPIDER: 0.1
    ZOMBIE_VILLAGER: 0.1
    PUFFERFISH: 0.1
    ENDERMITE: 0.05
    SILVERFISH: 0.05
    SLIME: 0.05
    PIG: 0.01
    SHEEP: 0.008
    COW: 0.008
    CHICKEN: 0.005
    SALMON: 0.005
    COD: 0.005
    RABBIT: 0.005
    TROPICAL_FISH: 0.001
    BAT: -0.05
    FOX: -0.1
    FROG: -0.1
    GOAT: -0.2
    PARROT: -0.3
    ARMADILLO: -0.3
    TURTLE: -0.3
    DOLPHIN: -0.3
    PANDA: -0.3
    POLAR_BEAR: -0.3
    OCELOT: -0.3
    LLAMA: -0.4
    BEE: -0.4
    MOOSHROOM: -0.4
    SKELETON_HORSE: -0.5
    STRIDER: -0.5
    AXOLOTL: -0.5
    MULE: -0.5
    DONKEY: -0.5
    HORSE: -0.5
    CAMEL: -0.5
    CAT: -0.5
    TRADER_LLAMA: -0.5
    ALLAY: -1.0
    WOLF: -1.0
    VILLAGER: -2.0
    WANDERING_TRADER: -2.0
Lives:
  cap: 2
  gameModeAfterLastDeath: Adventure
Teams:
  - Tideborn
  - Dalenii
  - Galactic
  - Trolls
AFK:
  #Time limit
  minutesAFK: 1

  #Checks if a player is AFK every x seconds and stores the data
  #More seconds -> Less accuracy less lag
  #Fewer seconds -> More accuracy more lag
  #Currently must be set to 1 for other hooked in functions. Will optimize these functions in the future to allow this to be adjusted in future.
  secondsInterval: 1

  # Messages
  afkWarning: "<bold><red>You will be marked afk ing <blue>%seconds% <red>seconds"
  kicked: "<red>You have been kicked for being AFK"